#%RAML 0.8
title: Jenkins_cicd_test
version: 1.0
baseUri: /mobile/custom/Jenkins_cicd_test
protocols: [HTTPS]
/employees:
  /{empid}:
    uriParameters:
      empid:
        displayName: empid
        type: string
    /fire:
    /vacation:
      /{vacationid}:
        uriParameters:
          vacationid:
            displayName: vacationid
            type: string
  /hire: